### ISSUE TITLE
Standalone configuration

### ISSUE THREAD

**Issue by sebdeckers** [myndzi/node-license-validator#2]
I love this tool. Thanks for creating it!

I'm finding that the list of exceptions grows too big for a reasonable single line in `package.json`.

Example:

``` json
{
  "scripts": {
    "audit": "node-license-validator --deep --production --allow-licenses ISC MIT BSD WTFPL BSD-2-Clause BSD-3-Clause Apache-2.0 CC-BY-3.0 Unlicense --allow-packages form-data@0.0.3 install@0.1.8 mime@1.2.7 request@2.11.4 wordwrap@0.0.2 yargs@1.3.3 jsonify@0.0.0 indexof@0.0.1 optimist@0.2.8 caniuse-db@1.0.30000339",
```

Is it possible to specify allowed licenses and allowed packages in a standalone file? E.g. `.nlvrc` or `nlv.json` perhaps. Alternatively they could be specified in `package.json` under a unique property like `nlv` (similar to how browserify works).

If you like the idea let me know. Happy to take a shot at this.

**Comment by myndzi** [comment]
...yep, that is pretty long. It's not a problem I had considered, really. Something like `--config <file>` makes sense and would allow a more natural format (such as a json array) in a more readable form. Seems like a good idea. I'm not terribly a fan of cluttering up the project directory with various "*rc" files, so leaving it as an argument leaves organization up to the user. Shouldn't be difficult to implement.

**Comment by sebdeckers** [comment]
Good call on making it configurable. Thanks!

**Comment by myndzi** [comment]
Published, and thanks
