### ISSUE TITLE
NPM 3 support for production

### ISSUE THREAD

**Issue by sebdeckers** [myndzi/node-license-validator#8]
@myndzi  Seems like since I upgraded to NPM 3 the `--production` flag is ignored. I get warnings for all dependencies. Is it because they are now installed in a flat directory structure?

**Comment by myndzi** [comment]
This seems to be fixed. I'm sorry I missed this issue before, I missed a lot of git notifications for a period as my e-mail filters were borked after the Github notification format change :(
