### ISSUE TITLE
Doesn't work with spdx 0.4.2

### ISSUE THREAD

**Issue by aleung** [myndzi/node-license-validator#9]
Because of kemitchell/spdx.js#16, node-license-validator doesn't work with spdx 0.4.2.
Have to specific spdx version to 0.4.1 in package.json:

```
"spdx": "0.4.1",
```

**Comment by aleung** [comment]
kemitchell/spdx.js#16 has been fixed. Works fine with spdx.js 0.4.3.

**Comment by myndzi** [comment]
That was easy ;)
